### ISSUE TITLE
Choosing user profile

### ISSUE THREAD

**Issue by HughP** [plandes/zotsite#11]
Greetings, I have multible Zotero Libraries. I switch between them with the -P flag. See this in the documentation: https://www.zotero.org/support/kb/multiple_profiles How do I make Zotsite connect to the correct library. Note: these are not collections. Zotsite does find one library but I want it to find a different one.

**Comment by plandes** [comment]
You can set the library in the `zosite.conf` file. It's the `data_dir` parameter.
Of course that only works if the two profiles are separated on the file system (I don't know anything about profiles).

Please let me know if this solves the issue for you.
