### ISSUE TITLE
.OperationalError: database is locked

### ISSUE THREAD

**Issue by daledali** [plandes/zotsite#13]
File "c:\users\mydjt\appdata\local\programs\python\python39\lib\site-packages\zensols\zotsite\db.py", line 174, in _select_collections
    for row in conn.execute(self._collection_sql(wparams)):
sqlite3.OperationalError: database is locked

**Comment by plandes** [comment]
It's customary to explain what the problem instead of a dump of some error.

Regarding what you left here: I assume you can't run the program because the Zotero is running at the same time (as explained in the documentation).
