### ISSUE TITLE
Zotsite cannot run on Windows

### ISSUE THREAD

**Issue by Thesharing** [plandes/zotsite#2]
When I run zotsite on Windows 10, I get the error: 

```shell
Traceback (most recent call last): 
File "c:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
File "c:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
File "C:\Anaconda\Scripts\zotsite.exe\__main__.py", line 9, in <module>
File "c:\anaconda\lib\site-packages\zensols\zotsite\cli.py", line 56, in main
    cl = ConfAppCommandLine()
File "c:\anaconda\lib\site-packages\zensols\zotsite\cli.py", line 14, in __init__
    default_config_file = '%s/.zotsiterc' % os.environ['HOME']
File "c:\anaconda\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
```

Zotsite cannot run on Windows because there is no environment variable `HOME` in Windows. I think maybe `%USERPROFILE%` is a good alternate.

**Comment by plandes** [comment]
I looks like you're using an old dependency. I don't use or know anaconda, but the vanilla python upgrade of these libraries would be:

```bash
pip install -U zensols.actioncli
pip install -U zensols.zotsite
```

Try that and also see the help option `--datadir`, which allows you to specify the location of your zotero DB.

**Comment by Trivy** [comment]
For the record, my computer is running Windows 7, I used `pip` instead of anaconda and I add the same error. 

To circumvent the problem, I had to use Git bash (!), together with the `--config` option, pointing to a configuration file containing the location of the Zotero DB.

Hope it helps!

**Comment by plandes** [comment]
@Trivy Thanks for this.  I wasn't aware of what git bash was until I read [this](https://stackoverflow.com/questions/17807485/what-is-the-exact-meaning-of-git-bash).  Seems to be some effort to emulate a UNIX environment in windows.
