### ISSUE TITLE
Download bibtex-entry from webpage

### ISSUE THREAD

**Issue by danielk333** [plandes/zotsite#21]
New feature:
It would be very useful for people browsing the publications if they could download the bibtex-entry for a item from the website, and/or the entire bibtex-file for all items listed on the site.

I could take a stab at a PR if I get some feasibility estimation from the author (and thanks for a super useful package)!

**Comment by plandes** [comment]
@danielk333 I'm closing this issue for now, but please do submit a pull request when/if you get around to implementing this.  There are probably JS libraries out there that could generate a BibTeX entry and all the metadata needed to do so lives in a JS data structure client side, so this probably wouldn't take long.
