### ISSUE TITLE
Zotsite doesn't find better-bibtex.sqlite

### ISSUE THREAD

**Issue by kasuar** [plandes/zotsite#28]
Since the access to better-bibtex.sqlite from outside Zotero has changed, zotfile doesn't work anymore in my Windows 11 installation of Zotero 6.0.27:
"Error: malformed database schema (autoexport_setting_insert) - trigger autoexport_setting_insert cannot reference objects in database betterbibtex" 
According to
https://github.com/retorquere/zotero-better-bibtex/issues/2684
there has to be issued the following code:
ATTACH DATABASE '<path to better-bibtex.sqlite>'  AS betterbibtex
As far as I understand @retorquere, this has to be done somewhere inside the zotsite code.
Anything I can do to fix it myself?

**Comment by retorquere** [comment]
I think this does it but I'm not in a position to test: https://github.com/plandes/zotsite/pull/29

**Comment by kasuar** [comment]
Thanks for suggesting a solution, @retorquere. Since I didn't manage to compile a test version of zotsite, I reverted to the older version zotero-better-bibtex-6.7.124.xpi which works fine for me.

**Comment by retorquere** [comment]
Zotero will automatically upgrade plugins every 48 hours I think, and I offer no support on older versions. It would be much better all around if @plandes applies the fix.

**Comment by kasuar** [comment]
You are absolutely right. To be safe for the time being, I switched off the auto-update feature for plugins. Since better-bibtex worked very well for me in the past ,I do not expect any trouble ahead.

**Comment by plandes** [comment]
This is now fixed.  Thanks everyone for seeing this before I did, and particularly @retorquere for the archaic SQLite `attach database` code 🙂.

I have [released version 0.8.2](https://github.com/plandes/zotsite/releases/tag/v0.8.2) and deployed. This should fix it @kasuar:

```bash
pip install -U zensols.zotsite
```

**Comment by kasuar** [comment]
Thanks for fixing. Works again as expected.
