### ISSUE TITLE
ImportError: No module named zensols.zotsite.cli

### ISSUE THREAD

**Issue by arteteco** [plandes/zotsite#3]
Hello all,
I installed zotsite via `pip install zensols.zotsite` in **debian 9**. No error.

When I try to give any command, I have the following output.
Am I missing something silly?

Thanks!

```
:~/Zotero$ zotsite print
Traceback (most recent call last):
  File "/usr/local/bin/zotsite", line 7, in <module>
    from zensols.zotsite.cli import main
ImportError: No module named zensols.zotsite.cli
```

**Comment by plandes** [comment]
Strange, I don't know why it can't find that module.  It should have installed with the program.  It sounds like an environment issue.  Is this anaconda?  What do you have your `PYTHONPATH` set to?  Sorry, but this error doesn't tell me a lot.

**Comment by arteteco** [comment]
Sorry if I wasn't much helpful, this was my whole output. Let's see if I can help you further here.
I have a fairly simple debian installation, didn't hack with paths.

I used `pip` which in debian 9 defaults to python2. Should I uninstall it and try with pip3/python3?

Meanwhile, hoping it helps,

```
>>> import sys
>>> print(sys.executable)
/usr/bin/python

```

```
tombom@blu:~$ python -c "import sys; print('\n'.join(sys.path))"

/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/home/tombom/.local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
```

**Comment by plandes** [comment]
Yes, it isn't tested under Python 2.7.  Thanks for noticing this--I thought I had documented that somewhere.  I have added a Python 3.6 badge to the page.

**Comment by arteteco** [comment]
It's cool, I'd just update the readme, in debian at least you need to specify pip3.

So, I uninstalled from pip and installed using pip3. Aaand nope, still not working, but different traceback

```
tombom@blu:~/Zotero$ zotsite print
Traceback (most recent call last):
  File "/usr/local/bin/zotsite", line 7, in <module>
    from zensols.zotsite import main
  File "/usr/local/lib/python3.5/dist-packages/zensols/zotsite/__init__.py", line 8, in <module>
    from zensols.zotsite.cli import *
  File "/usr/local/lib/python3.5/dist-packages/zensols/zotsite/cli.py", line 2, in <module>
    from zensols.actioncli import OneConfPerActionOptionsCli
  File "/usr/local/lib/python3.5/dist-packages/zensols/actioncli/__init__.py", line 2, in <module>
    from zensols.actioncli.persist import *
  File "/usr/local/lib/python3.5/dist-packages/zensols/actioncli/persist.py", line 59
    self.varname = f'_{cstr}_{fname}_pwvinst'
                                            ^
SyntaxError: invalid syntax

```

My env paths, if they can be of any help.

```
tombom@blu:~/Zotero$ python3 -c "import sys; print(sys.executable)"
/usr/bin/python3
```


```
tombom@blu:~/Zotero$ python3 -c "import sys; print('\n'.join(sys.path))"

/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
/home/tombom/.local/lib/python3.5/site-packages
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
```
Thanks a bunch for your help,  @plandes !

**Comment by plandes** [comment]
You need Python 3.6.  You're using 3.5, which didn't have the `f` syntax.

**Comment by plandes** [comment]
Also, regarding pip.  Most installs have that aliased to pip3 as python 2.7 is considered by most very old.

**Comment by arteteco** [comment]
Thanks @plandes . I love debian but I hate debian, there is no 3.6 available, I should build from source.

I'll report back in case of troubles with >=3.6, but my feeling is that it's really just a version problem.

**Comment by plandes** [comment]
Sounds good.  These days I almost always have to compile from source.  If you're going to do that I'd recommend just going right to 3.6.8.
