### ISSUE TITLE
Include groups

### ISSUE THREAD

**Issue by murrayireland** [plandes/zotsite#5]
It would be great if group libraries could be exported as well.

**Comment by plandes** [comment]
I agree, but I don't have a need for this, nor do I have the time to implement it.  Would you be interested in submitting a contribution to the project for this?

**Comment by murrayireland** [comment]
Sure, I'm happy to give it a shot!

**Comment by plandes** [comment]
Sounds good.  Please create a pull request and I'll take a look.  Let me know if there's anything you need.
