### ISSUE TITLE
Environment for Windows

### ISSUE THREAD

**Issue by Aroc76** [plandes/zotsite#7]
Hi! 
I am trying to use zotsite (version 0.2.3) for Windows 10 as OS. Unfortunaly an error occurs calling zotsite from the command line. The error indicates that the environment 'Home' defined in cli.py is inkown. According to this [link](https://stackoverflow.com/questions/14742064/python-os-environhome-works-on-idle-but-not-in-a-script) 'Home' is unkown in Windows OS. Therefor I changed the cli.py from
                `default_config_file = '%s/.zotsiterc' % os.environ['HOME']`
to 
```
            if platform.system()=='Linux':
                default_config_file = '%s/.zotsiterc' % os.environ['HOME']
            if platform.system()=='Windows':
                default_config_file = '%s/.zotsiterc' % os.path.expanduser('~')
```
and added 'import platform'.

But unfortunaly a new error occurs:

> Traceback (most recent call last):
>   File "c:\users\XXXX\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\XXXX\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\XXXX\AppData\Local\Programs\Python\Python37-32\Scripts\zotsite.exe\__main__.py", line 9, in <module>
>   File "c:\users\friebe\appdata\local\programs\python\python37-32\lib\site-packages\zensols\zotsite\cli.py", line 62, in main
>     cl.invoke()
>   File "c:\users\XXXX\appdata\local\programs\python\python37-32\lib\site-packages\zensols\actioncli\simple.py", line 198, in invoke
>     meth, exec_obj = self.create_executor(args)
>   File "c:\users\XXXX\appdata\local\programs\python\python37-32\lib\site-packages\zensols\actioncli\simple.py", line 176, in create_executor
>     config = self.get_config(params)
>   File "c:\users\XXXX\appdata\local\programs\python\python37-32\lib\site-packages\zensols\actioncli\peraction.py", line 236, in get_config
>     logger.debug('created config: %s' % conf)
>   File "c:\users\XXXX\appdata\local\programs\python\python37-32\lib\site-packages\zensols\actioncli\config.py", line 327, in __str__
>     format(self.config_file, self.sections))
>   File "c:\users\XXXX\appdata\local\programs\python\python37-32\lib\site-packages\zensols\actioncli\config.py", line 287, in sections
>     secs = self.parser.sections()
>   File "c:\users\XXXX\appdata\local\programs\python\python37-32\lib\site-packages\zensols\actioncli\config.py", line 179, in parser
>     raise IOError('no such file: {cfile}')
> OSError: no such file: {cfile}

BTW after installing zotsite, no '/.zotsiterc' was created in the Home-Environment.

I will appreciate any help.

Best regards!

**Comment by plandes** [comment]
You shouldn't need to do this.  Setting the environment variable `ZOTSITERC` overrides looking for the configuration in the home directory.  In Windows you set environment variables in some system properties dialog somewhere where you also configure `PATH` etc.  This is documented [here](https://github.com/plandes/zotsite#configuration-file).  Let me know if that works for you.

**Comment by Aroc76** [comment]
Thanks for your fast response! 
I placed a new environment variable within the system namen `ZOTESITERC`. The value of this  variable was set to `C:\Path\To\ZOTSITE\zotsite.ini`. Within this ini-file i wrote the position of the Zotero-Database:
```
[default]
data_dir=X:\Pathl\To\Zotero
```
The result:

- The new environment is accepted, there are no further problems with the 'Home'-environment.
- `zotsite print`... works!
- `zotesite export -o X:\Path\To\HTML`....works!

Thanks a lot!

**Comment by plandes** [comment]
Glad I could help and that this was so easy.

Cheers.
